### ISSUE TITLE
Compile error when running dotnet run on a SAFE template project after including FS.FluentUI

### ISSUE THREAD

**Issue by Walms** [sydsutton/FS.FluentUI#1]
Hi, 

Thanks for your work on this. You let me know about it on Twitter. I've been having a play and noticed the following output when running my project. 

`client: .\output\fable_modules\FS.FluentUI.0.0.1-beta09\Domain.fs(204,50): (204,67) error FSHARP: Discriminated union cases and exception labels must be uppercase identifiers (code 53)`

Let me know if you'd like any more info.

**Comment by sydsutton** [comment]
@Walms I believe that's because of a conflict between the SDK in my global.json I had and the version of FSharp.Core I had specified. Please try updating the 0.0.1-beta11 and tell me if you get the same error. Thanks for the first issue, btw!

**Comment by sydsutton** [comment]
@Walms is it okay if I close this issue, or do you get the same compilation errors with beta-12 (now 1.0.0-prerelease-001)?
