### ISSUE TITLE
[Enhancement] Drawer Header Title attribute/styling

### ISSUE THREAD

**Issue by shayanhabibi** [sydsutton/FS.FluentUI#12]
## Issue

Customizing the drawer to be a navigation persisting vertical bar which can expand from icon only to show the text for the menu items is not compatible with the drawerHeaderTitle without being able to clip the text, there does not seem to be any way to access the attributes/style of the header title without introducing a nested element.

## Criticality

While this would be important in following the principle of customisability, it is not imperative to include since the EoY will likely see finalisation of the nav component which will replace this pattern

## What have I tried

I'll admit I'm not experienced with web technologies, if you are succesful in applying this pattern I would appreciate your guidance

## Example

> Note that this example is not functional, but is supposed to demonstrate clearly the behaviour that is occurring in comparison to the behaviour that is expected as is the case with the tablist contents within the drawer.

```fs
[<ReactComponent>]
let DrawerExample() =
    let isOpen, setIsOpen = React.useState true

    let expandAction lambda = drawerHeaderTitle.action (
        Fui.button [
            button.appearance.subtle
            button.ariaLabel "subtle"
            button.icon (
                Fui.icon.arrowExpandRegular [ icon.size.``48`` ]
            )
            button.onClick lambda
        ]
    )

    let container ( children : ReactElement list ) =
        Fui.inlineDrawer [
            inlineDrawer.open' true
            inlineDrawer.separator true
            inlineDrawer.style [
                style.width (if isOpen then 240 else 120)
                style.transitionProperty transitionProperty.width
                style.transitionDurationMilliseconds 250
            ]

            inlineDrawer.children children
        ]

    let header =
        Fui.drawerHeader [
            Fui.drawerHeaderTitle [
                expandAction ( fun _ -> isOpen |> not |> setIsOpen )
                drawerHeaderTitle.text "Overlay Drawer"
                // drawerHeaderTitle.text.wrap false
            ]
        ]
    let body =
        Fui.drawerBody [
            drawerBody.children [
                Fui.tabList [
                    tabList.vertical true
                    tabList.appearance.subtle
                    tabList.size.large
                    tabList.onTabSelect (fun (d: ValueProp<string>) -> printfn "value %A" d.value)
                    tabList.children [
                        Fui.tab [
                            tab.value "tab1"
                            tab.icon (
                                Fui.icon.homeFilled [ icon.size.``16`` ]
                            )
                            tab.children [ Fui.text [ text.wrap false ; text.text "First tab" ] ]
                        ]
                    ]
                ]
            ]
        ]

    container [
        header
        body
    ]
```

**Comment by shayanhabibi** [comment]
It's important to point out that I know the above pattern is not necessary to achieve the listed goal, but it is a pattern which I would find useful in multiple regards.

I think it's more important to address that I am attempting to prevent the title from wrapping without causing the action button to be offset outside the visible view of the drawer.

Hopefully that makes sense?

**Comment by sydsutton** [comment]
I think that what you may be looking for is something LIKE this (but probably not exactly this)? Let me know.
```fsharp
    let header =
        Fui.drawerHeader [
            Fui.drawerHeaderTitle [
                drawerHeaderTitle.heading [
                    prop.text "Overlay Drawer"
                    prop.style [ style.maxWidth (if isOpen then 450 else 50) ]
                ]
                expandAction ( fun _ -> isOpen |> not |> setIsOpen )
            ]
        ]
```

**Comment by sydsutton** [comment]
@shayanhabibi no problem, glad I could help!
