### ISSUE TITLE
Add bindings for useRestoreFocusTarget

### ISSUE THREAD

**Issue by cody-quinn** [sydsutton/FS.FluentUI#19]
Bindings for the hook [`useRestoreFocusTarget`](https://react.fluentui.dev/?path=/docs/utilities-focus-management-userestorefocussource--docs) from `@fluentui/react-components` are missing.

**Comment by sydsutton** [comment]
Added in recent commit (https://github.com/sydsutton/FS.FluentUI/commit/a28e3054c32907dea24a2573363f9fa6fe32189a) and will be with next version bump. Thanks!
